-- 트랜잭션 - 작업수행단위(데이터베이스 안전장치)---

--트랜잭션 현상태
SHOW AUTOCOMMIT;

SET AUTOCOMMIT ON; -- 모든 쿼리문이 자동 COMMIT된다.
SET AUTOCOMMIT OFF;

SELECT *
  FROM DEPTS;
  
DELETE FROM DEPTS
 WHERE DEPARTMENT_ID = 10;

--세이브포인트 생성
SAVEPOINT DELETE_10;

DELETE FROM DEPTS
 WHERE DEPARTMENT_ID = 20;
SAVEPOINT DELETE_20;

DELETE FROM DEPTS;
SAVEPOINT DELETE_ALL;

ROLLBACK TO DELETE_20;
ROLLBACK;