---- 테이블 생성----
CREATE TABLE DEPT (
    DEPTNO  NUMBER(2, 0), --2자리 저장, 실수는 저장하지 않는다.
    DNAME   VARCHAR2(14), --BYTE기반 가변 문자열, 
    LOC     VARCHAR2(13),
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10)
);

SELECT *
  FROM DEPT;

INSERT INTO DEPT
VALUES (99, '영업', '서울', SYSDATE, 2000000000);
  
DESC DEPT;


--- 테이블 수정 ALTER TABLE----
ALTER TABLE DEPT
ADD DEPT_COUNT NUMBER(3); -- 추가

ALTER TABLE DEPT
MODIFY DEPT_COUNT NUMBER(10); -- 수정

ALTER TABLE DEPT
RENAME COLUMN DEPT_COUNT TO EMP_COUNT; -- 칼럼명 변경

ALTER TABLE DEPT
DROP COLUMN EMP_COUNT; -- 삭제


-- 테이블 삭제
DROP TABLE DEPT;
-- 해당 테이블에 FK제약조건이 들어있더라도 삭제를 진행.
DROP TABLE CASCADE CONSTRAINTS 제약조건명; 


--테이블 데이터 전부 삭제
TRUNCATE TABLE DEPT;

SELECT *
  FROM DEPT;
DESC DEPT;



-- 테이블 생성과 제약조건
/*
열레벨 제약조건(PK, FK, NOT NULL, CHECK, UNIQUE)
1. PK - 테이블 고유 식별 칼럼(NOT NULL + UNIQUE)
PRIMARY KEY
2. UNIQUE = 유일한 값을 갖게하는 칼럼(중복데이터의 방지)
3. NOT NULL - NULL을 허용하지 않는다.
4. FK - 참조하는 테이블의 PK를 저장하는 칼럼
FOREIGN KEY
5. CHECK - 정의된 형식만 들어오도록 허용

*/

CREATE TABLE DEPT (
    DEPT_NO NUMBER(2) CONSTRAINT DEPT_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(14) NOT NULL UNIQUE,
    LOCA NUMBER(4) REFERENCES LOCATIONS(LOCATION_ID),
    -- 아무것도 지정하지 않으면 기본으로 지금시간을 지정
    DEPT_DATE DATE DEFAULT SYSDATE,
    DEPT_BONUS NUMBER(10),
    DEPT_GENDER CHAR(1) CHECK(DEPT_GENDER IN ('F','M'))
);

DROP TABLE DEPT;

/*
테이블 레벨 제약조건(모든 열을 선언한 후에 아래쪽에 제약조건 추가)
NOT NULL이나 DEFAULT는 나중에 지정이 안된다.
같이 지정해야한다.

제약조건 추가 
제약조건 제약조건_이름 제약조건_종류 적용칼럼
*/
;
CREATE TABLE DEPT(
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR(14) NOT NULL,
    LOCA NUMBER(4),
    DEPT_DATE DATE DEFAULT SYSDATE,
    DEPT_BONUS NUMBER(10),
    DEPT_GENDER CHAR(1),
    CONSTRAINT DEPT_DEPT_NO_PK PRIMARY KEY (DEPT_NO),
    CONSTRAINT DEPT_DEPT_NAME_UK UNIQUE (DEPT_NAME),
    CONSTRAINT DEPT_DEPT_GENDER_CK CHECK (DEPT_GENDER IN ('F', 'M')),
    CONSTRAINT DEPT_LOCA_LOCATION_LOCATION_ID_FK 
        FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)  
);

DROP TABLE DEPT;


SELECT FIRST_NAME
          FROM EMPLOYEES;
          
SELECT (SELECT FIRST_NAME
          FROM EMPLOYEES E2
         WHERE E1.EMPLOYEE_ID = E2.EMPLOYEE_ID
        ) AS FIRST_NAME
  FROM EMPLOYEES E1;
  
SELECT (SELECT FIRST_NAME
          FROM EMPLOYEES E2
        ) AS FIRST_NAME
  FROM DUAL;
  
