---- 테이블 생성----
CREATE TABLE DEPT (
    DEPTNO  NUMBER(2, 0), --2자리 저장, 실수는 저장하지 않는다.
    DNAME   VARCHAR2(14), --BYTE기반 가변 문자열, 
    LOC     VARCHAR2(13),
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10)
);

SELECT *
  FROM DEPT;

INSERT INTO DEPT
VALUES (99, '영업', '서울', SYSDATE, 2000000000);
  
DESC DEPT;


--- 테이블 수정 ALTER TABLE----
ALTER TABLE DEPT
ADD DEPT_COUNT NUMBER(3); -- 추가

ALTER TABLE DEPT
MODIFY DEPT_COUNT NUMBER(10); -- 수정

ALTER TABLE DEPT
RENAME COLUMN DEPT_COUNT TO EMP_COUNT; -- 칼럼명 변경

ALTER TABLE DEPT
DROP COLUMN EMP_COUNT; -- 삭제


-- 테이블 삭제
DROP TABLE DEPT;
-- 해당 테이블에 FK제약조건이 들어있더라도 삭제를 진행.
DROP TABLE CASCADE CONSTRAINTS 제약조건명; 


--테이블 데이터 전부 삭제
TRUNCATE TABLE DEPT;

SELECT *
  FROM DEPT;
DESC DEPT;



-- 테이블 생성과 제약조건
/*
열레벨 제약조건(PK, FK, NOT NULL, CHECK, UNIQUE)
1. PK - 테이블 고유 식별 칼럼(NOT NULL + UNIQUE)
PRIMARY KEY
2. UNIQUE = 유일한 값을 갖게하는 칼럼(중복데이터의 방지)
3. NOT NULL - NULL을 허용하지 않는다.
4. FK - 참조하는 테이블의 PK를 저장하는 칼럼
FOREIGN KEY
5. CHECK - 정의된 형식만 들어오도록 허용

*/

CREATE TABLE DEPT (
    DEPT_NO NUMBER(2) CONSTRAINT DEPT_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(14) NOT NULL UNIQUE,
    LOCA NUMBER(4) REFERENCES LOCATIONS(LOCATION_ID),
    -- 아무것도 지정하지 않으면 기본으로 지금시간을 지정
    DEPT_DATE DATE DEFAULT SYSDATE,
    DEPT_BONUS NUMBER(10),
    DEPT_GENDER CHAR(1) CHECK(DEPT_GENDER IN ('F','M'))
);

DROP TABLE DEPT;

/*
테이블 레벨 제약조건(모든 열을 선언한 후에 아래쪽에 제약조건 추가)
NOT NULL이나 DEFAULT는 나중에 지정이 안된다.
같이 지정해야한다.

제약조건 추가 
제약조건 제약조건_이름 제약조건_종류 적용칼럼
*/
;
CREATE TABLE DEPT(
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR(14) NOT NULL,
    LOCA NUMBER(4),
    DEPT_DATE DATE DEFAULT SYSDATE,
    DEPT_BONUS NUMBER(10),
    DEPT_GENDER CHAR(1),
    CONSTRAINT DEPT_DEPT_NO_PK PRIMARY KEY (DEPT_NO),
    CONSTRAINT DEPT_DEPT_NAME_UK UNIQUE (DEPT_NAME),
    CONSTRAINT DEPT_DEPT_GENDER_CK CHECK (DEPT_GENDER IN ('F', 'M')),
    CONSTRAINT DEPT_LOCA_LOCATION_LOCATION_ID_FK 
        FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)  
);

DROP TABLE DEPT;


SELECT FIRST_NAME
          FROM EMPLOYEES;
          
SELECT (SELECT FIRST_NAME
          FROM EMPLOYEES E2
         WHERE E1.EMPLOYEE_ID = E2.EMPLOYEE_ID
        ) AS FIRST_NAME
  FROM EMPLOYEES E1;
  
SELECT (SELECT FIRST_NAME
          FROM EMPLOYEES E2
        ) AS FIRST_NAME
  FROM DUAL;
  
  
  
--제약 조건은 추가, 삭제가 가능하다.
DROP TABLE DEPT;
DROP TABLE DEPT2;

CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2),
    DEPT_NAME VARCHAR(14),
    LOCA NUMBER(4),
    DEPT_DATE DATE DEFAULT SYSDATE,
    DEPT_BONUS NUMBER(10),
    DEPT_GENDER CHAR(1)  
);

--PK 추가
ALTER TABLE DEPT2
ADD CONSTRAINT DEPT2_DEPT_NO_PK PRIMARY KEY(DEPT_NO);

-- FK 추가
ALTER TABLE DEPT2
ADD CONSTRAINT DEPT2_LOCA_LOCATIONS_LOCATION_ID_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID);

--CHECK추가
ALTER TABLE DEPT2
ADD CONSTRAINT DEPT2_DEPT_GENDER_CK CHECK (DEPT_GENDER IN ('F', 'M'));

--UNIQUE추가
ALTER TABLE DEPT2
ADD CONSTRAINT DEPT2_DEPT_NAME_UK UNIQUE (DEPT_NAME);

--NOT NULL은 열 수정형태로 변경한다.
ALTER TABLE DEPT2
MODIFY DEPT_NAME VARCHAR(14) NOT NULL;


DESC DEPT2;
--제약조건 삭제 (제약조건 이름으로)
ALTER TABLE DEPT2
DROP CONSTRAINT DEPT2_DEPT_NO;

--FK는 부모테이블에 값이 없다면 삽입이 불가능
INSERT INTO DEPT2
VALUES (10, 'TEST', 100, SYSDATE, 5000, 'F');--에러남 LOCATIONS의 LOCATION_ID에는 100이라는 값이 없기 때문이다.



CREATE TABLE MEMBERS(
    M_NAME VARCHAR2(10) NOT NULL,
    M_NUM NUMBER(3)     CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY,
    REG_DATE DATE       NOT NULL CONSTRAINT MEME_REGDATE_UK UNIQUE,
    GENDER VARCHAR2(1),
    LOCA NUMBER(4)      CONSTRAINT MEM_LOCA_LOC_LOCID_FK 
                        REFERENCES LOCATIONS(LOCATION_ID)
);

CREATE TABLE MEMBERS(
    M_NAME VARCHAR2(10) NOT NULL,
    MN_NUM NUMBER(3),
    REG_DATE DATE,
    GENDER VARCHAR2(1),
    LOCA NUMBER(4),
    CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY (M_NAME),
    CONSTRAINT MEM_REGDATE_UK UNIQUE (REG_DATE),
    CONSTRAINT MEM_LOCA_LOC_LOCID_FK FOREIGN KEY (LOCA)
        REFERENCES LOCATIONS(LOCATION_ID)
);

CREATE TABLE MEMBERS(
    M_NAME VARCHAR2(10),
    M_NUM NUMBER(2),
    REG_DATE DATE,
    GENDER VARCHAR2(2),
    LOCA NUMBER(4)
);

ALTER TABLE MEMBERS
MODIFY M_NAME VARCHAR2(10) NOT NULL;
ALTER TABLE MEMBERS
ADD CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY (M_NUM);
ALTER TABLE MEMBERS
ADD CONSTRAINT MEM_REGDATE_UK UNIQUE (REG_DATE);
ALTER TABLE MEMBERS
ADD CONSTRAINT MEM_LOCA_LOC_LOCID_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID);
ALTER TABLE MEMBERS
MODIFY REG_DATE DATE DEFAULT SYSDATE;
DESC MEMBERS;

DROP TABLE MEMBERS;

INSERT INTO MEMBERS(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('AAA', 1, '2018-07/01', 'M', 1800);

INSERT INTO MEMBERS(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('BBB', 2, '2018/07/02', 'F', 1900);

INSERT INTO MEMBERS(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('CCC', 3, '2018/07-03', 'M', 2000);

INSERT INTO MEMBERS(M_NAME, M_NUM, REG_DATE, GENDER, LOCA)
VALUES('DDD', 4, SYSDATE, 'M', 2000);

SELECT *
  FROM MEMBERS;
  
SELECT M_NAME, M_NUM, STREET_ADDRESS, LOCATION_ID
  FROM MEMBERS M INNER JOIN LOCATIONS L
ON M.LOCA = L.LOCATION_ID
ORDER BY M_NUM;