SELECT COUNT(*)
  FROM EMPLOYEES;
  
SELECT COUNT(*)
  FROM EMPLOYEES E
LEFT OUTER JOIN EMPLOYEES E2
ON E.MANAGER_ID = E2.EMPLOYEE_ID;

---1-----------------------------

SELECT DEPTNO, DNAME, EMPNO, ENAME, SAL
  FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
 WHERE SAL >= 2000;

SELECT DEPTNO, DNAME, EMPNO, ENAME, SAL
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND SAL >= 2000;

---2---------------------------

SELECT D.DEPTNO, D.DNAME, AVG(E.SAL) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL,
        MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
  FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME, AVG(E.SAL) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL,
        MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

--3---------------------------------------------

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
  FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.ENAME;


SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
  FROM EMP E, DEPT D
 WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DEPTNO, E.ENAME;

---4------------------------

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL,
        D.LOSAL, D.HISAL, D.GRADE, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGER_ENAME
  FROM EMP E
LEFT OUTER JOIN EMP E2
ON E.MGR = E2.EMPNO
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.EMPNO;


SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL,
        D.LOSAL, D.HISAL, D.GRADE, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGER_ENAME
  FROM EMP E, EMP E2, DEPT D
 WHERE E.MGR = E2.EMPNO(+)
   AND E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.EMPNO;

