-- 그룹 함수 AVG, MAX, MIN, SUM, COUNT
SELECT AVG(SALARY),
       SUM(SALARY),
       MIN(SALARY),
       MAX(SALARY),
       COUNT(*)
  FROM EMPLOYEES;
  
-- COUNT(*) 해당 테이블의 데이터 개수
SELECT COUNT(*)
  FROM EMPLOYEES;


-- 그룹함수는 일반 칼럼과 동시에 사용이 불가능하다.
-- 그룹 절에 묶인 칼럼만 SELECT절에서 이용 가능하다.
SELECT DEPARTMENT_ID, SUM(SALARY)
  FROM EMPLOYEES;
  
  
-- 칼럼 값중에 NULL값이 아닌 데이터의 개수
SELECT COUNT(FIRST_NAME)
  FROM EMPLOYEES;

-- GROUP BY절을 이용한 그룹핑
-- GROUP BY절은 WHERE절 다음에 들어간다.
SELECT DEPARTMENT_ID, SUM(SALARY)
  FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SUM(SALARY), AVG(SALARY), COUNT(*)
  FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;


-- 2개 이상의 그룹화
SELECT DISTINCT DEPARTMENT_ID, JOB_ID
  FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;

-- WHERE절에는 그룹함수를 사용할 수 없다.

/*
WHERE 절은 처음에 가져올 테이블에서 행을 뽑을 때의 조건을 설정하는 것이다.
GROUP BY 절의 조건 HAVING
GROUP BY 절로 묶은 그룹에 대한 조건식 HAVING
*/

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2)
  FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 8000;

SELECT DEPARTMENT_ID,
       SUM(SALARY),
       COUNT(*)
  FROM EMPLOYEES
 WHERE SALARY >= 15000
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

--GROUP BY 절의 조건 HAVING
SELECT DEPARTMENT_ID,
       SUM(SALARY)
  FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY) >= 8000
ORDER BY DEPARTMENT_ID;

SELECT JOB_ID, COUNT(*)
  FROM EMPLOYEES
GROUP BY JOB_ID
--HAVING COUNT(*) >= 20
ORDER BY JOB_ID;