

/* Create Tables */

CREATE TABLE BOOK
(
	BOOK_NUM number(10,0) NOT NULL,
	BOOK_NAME varchar2(40) NOT NULL,
	STATUS char(1) NOT NULL,
	CODE number(3) NOT NULL,
	PRIMARY KEY (BOOK_NUM)
);


CREATE TABLE MEMBER_TEST
(
	MEMBER_NUM number(10,0) NOT NULL,
	MEMBER_NAME varchar2(20) NOT NULL,
	MEMBER_PHONE varchar2(20) NOT NULL,
	PRIMARY KEY (MEMBER_NUM)
);


CREATE TABLE RENT_LIST
(
	RENT_NUM number(10,0) NOT NULL,
	RETURN_DATE date NOT NULL,
	MEMBER_NUM number(10,0) NOT NULL,
	BOOK_NUM number(10,0) NOT NULL,
	PRIMARY KEY (RENT_NUM)
);



/* Create Foreign Keys */

ALTER TABLE RENT_LIST
	ADD FOREIGN KEY (BOOK_NUM)
	REFERENCES BOOK (BOOK_NUM)
;


ALTER TABLE RENT_LIST
	ADD FOREIGN KEY (MEMBER_NUM)
	REFERENCES MEMBER_TEST (MEMBER_NUM)
;



